In [1]:
import pandas as pd

In [2]:
def read_data(file_path):
    df = pd.read_csv(file_path, delimiter='\t')
    df = df.T
    df = df.rename_axis('case_id').reset_index()
    return df

In [3]:
file_path = './data/CPTAC/DISCOVERY_data_freeze_v_2.1/UCEC_discovery_Proteomics_PNNL_ratio_median_polishing_log2.txt'
df_proteo = read_data(file_path)
df_proteo

,case_id,A1BG,A2M,A2ML1,A4GALT,AAAS,AACS,AADAT,AAED1,AAGAB,...,ZSWIM8,ZSWIM9,ZW10,ZWILCH,ZWINT,ZXDC,ZYG11B,ZYX,ZZEF1,ZZZ3
0,S001,-1.180,-0.8630,-0.8020,0.2220,0.2560,0.6650,1.2800,-0.3390,0.4120,...,-0.08770,NaN,0.02290,0.1090,NaN,-0.332,-0.43300,-1.020,-0.12300,-0.0859
1,S002,-0.685,-1.0700,-0.6840,0.9840,0.1350,0.3340,1.3000,0.1390,1.3300,...,-0.03560,NaN,0.36300,1.0700,0.7370,-0.564,-0.00461,-1.130,-0.07570,-0.4730
2,S003,-0.528,-1.3200,0.4350,NaN,-0.2400,1.0400,-0.0213,-0.0479,0.4190,...,0.00112,-0.1450,0.01050,-0.1160,NaN,0.151,-0.07400,-0.540,0.32000,-0.4190
3,S005,-1.670,-1.1900,-0.4430,0.2430,-0.0993,0.7570,0.7400,-0.9290,0.2290,...,0.07250,-0.0552,-0.07140,0.0933,0.1560,-0.398,-0.07520,-0.797,-0.03010,-0.4670
4,S006,-0.374,-0.0206,-0.5370,0.3110,0.3750,0.0131,-1.1000,NaN,0.5650,...,-0.17600,NaN,-1.22000,-0.5620,0.9370,-0.646,0.20700,-1.850,-0.17600,0.0513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,S099,-1.070,-0.7120,0.0462,-0.0471,0.2270,1.3500,1.2100,0.0048,0.6820,...,-0.06990,-0.4010,0.55700,0.8270,0.3480,-0.187,-0.10700,-0.830,0.06200,-0.5280
91,S100,-1.280,-0.7360,-0.5520,0.1140,0.2730,1.0700,0.8500,NaN,-0.5360,...,0.13100,NaN,-0.00364,0.7630,0.0784,-0.203,0.01320,-1.200,-0.35700,0.0299
92,S101,-0.290,-0.3200,3.1700,-0.9070,0.0317,-0.0425,NaN,-0.2730,-0.0747,...,-0.17900,-0.5210,0.05230,0.5150,0.5850,0.138,-0.19000,-0.966,-0.00627,-0.2490
93,S102,0.266,1.3900,-0.0655,0.4700,0.3980,-0.1340,0.4610,1.0400,0.3630,...,-0.14000,NaN,-0.01220,0.2500,0.5530,0.387,0.06420,-0.437,0.10400,-0.4980
94,S103,0.692,0.5890,0.5870,NaN,-0.0835,0.1720,-0.2150,0.0140,-0.1460,...,-0.02250,0.2980,-0.12400,0.1780,0.1470,-0.114,0.13700,1.240,0.00682,-0.0233

In [4]:
df_sommut = read_data('./data/CPTAC/DISCOVERY_data_freeze_v_2.1/UCEC_discovery_somatic_mutation_gene_level.txt')
df_sommut

,case_id,A1BG,A1CF,A2M,A2ML1,A3GALT2,A4GALT,A4GNT,AAAS,AACS,...,ZUFSP,ZWILCH,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,S001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,S002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,S003,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,S005,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,S006,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,S099,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,1,0,0,0
91,S100,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92,S101,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93,S102,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94,S103,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df_cna = read_data('./data/CPTAC/DISCOVERY_data_freeze_v_2.1/UCEC_discovery_WGS_CNA_gene_level_THRESHOLD.txt')
df_cna

,case_id,DDX11L1,FAM138A|chr1,FAM87B,LOC100133331|chr1,LOC100288069,LOC729737,MIR6723,MIR6859-1|chr1,OR4F16|chr1,...,DAZ3,TTTY3,CDY1,CSPG4P1Y,GOLGA2P2Y,TTTY3B,DDX11L16|chrY,IL9R|chrY,SPRY3|chrY,VAMP7|chrY
0,S001,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,S002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,S003,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,S005,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,S006,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,S099,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
91,S100,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,0,0,0,0,0,0,0,0,0,0
92,S101,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
93,S102,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
94,S103,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df_sommut.sum(axis=0, numeric_only=True).sort_values(ascending=False).head(10)

PTEN      75
PIK3CA    47
ARID1A    43
PIK3R1    37
KRAS      31
CTNNB1    29
CTCF      27
KMT2B     23
ZFHX3     21
TP53      21
dtype: int64

In [7]:
merged_df = df_proteo.merge(df_sommut, on='case_id', suffixes=('_proteo', '_sommut'))
merged_df

,case_id,A1BG_proteo,A2M_proteo,A2ML1_proteo,A4GALT_proteo,AAAS_proteo,AACS_proteo,AADAT_proteo,AAED1,AAGAB_proteo,...,ZUFSP,ZWILCH_sommut,ZXDA,ZXDB,ZXDC_sommut,ZYG11A,ZYG11B_sommut,ZYX_sommut,ZZEF1_sommut,ZZZ3_sommut
0,S001,-1.180,-0.8630,-0.8020,0.2220,0.2560,0.6650,1.2800,-0.3390,0.4120,...,0,0,0,0,0,0,0,0,0,0
1,S002,-0.685,-1.0700,-0.6840,0.9840,0.1350,0.3340,1.3000,0.1390,1.3300,...,0,0,0,0,0,0,0,0,0,0
2,S003,-0.528,-1.3200,0.4350,NaN,-0.2400,1.0400,-0.0213,-0.0479,0.4190,...,0,0,0,0,0,0,0,0,0,0
3,S005,-1.670,-1.1900,-0.4430,0.2430,-0.0993,0.7570,0.7400,-0.9290,0.2290,...,0,0,0,0,0,0,0,0,0,0
4,S006,-0.374,-0.0206,-0.5370,0.3110,0.3750,0.0131,-1.1000,NaN,0.5650,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,S099,-1.070,-0.7120,0.0462,-0.0471,0.2270,1.3500,1.2100,0.0048,0.6820,...,1,0,0,0,0,0,1,0,0,0
91,S100,-1.280,-0.7360,-0.5520,0.1140,0.2730,1.0700,0.8500,NaN,-0.5360,...,0,0,0,0,0,0,0,0,0,0
92,S101,-0.290,-0.3200,3.1700,-0.9070,0.0317,-0.0425,NaN,-0.2730,-0.0747,...,0,0,0,0,0,0,0,0,0,0
93,S102,0.266,1.3900,-0.0655,0.4700,0.3980,-0.1340,0.4610,1.0400,0.3630,...,0,0,0,0,0,0,0,0,0,0
94,S103,0.692,0.5890,0.5870,NaN,-0.0835,0.1720,-0.2150,0.0140,-0.1460,...,0,0,0,0,0,0,0,0,0,0

In [8]:
correlations = merged_df.corr(numeric_only=True)
correlations

,A1BG_proteo,A2M_proteo,A2ML1_proteo,A4GALT_proteo,AAAS_proteo,AACS_proteo,AADAT_proteo,AAED1,AAGAB_proteo,AAK1_proteo,...,ZUFSP,ZWILCH_sommut,ZXDA,ZXDB,ZXDC_sommut,ZYG11A,ZYG11B_sommut,ZYX_sommut,ZZEF1_sommut,ZZZ3_sommut
A1BG_proteo,1.000000,0.668930,0.129737,0.125693,-0.133788,-0.347029,-0.229781,0.042169,-0.048411,0.153237,...,-0.159953,-0.029480,0.019870,-0.127285,0.013853,-0.079465,-0.157926,-0.124692,-0.029678,0.023839
A2M_proteo,0.668930,1.000000,0.137645,0.094538,0.034448,-0.251096,-0.072371,0.093278,0.031651,0.052590,...,-0.051961,-0.003025,0.050268,-0.016362,-0.033843,-0.003671,-0.051510,-0.097939,0.058407,0.048919
A2ML1_proteo,0.129737,0.137645,1.000000,0.103499,-0.206183,0.041496,-0.076818,-0.083662,0.133702,0.008633,...,-0.097727,-0.148260,-0.117542,-0.084775,-0.023204,NaN,-0.043936,-0.107738,0.051249,-0.156473
A4GALT_proteo,0.125693,0.094538,0.103499,1.000000,-0.185359,0.213150,-0.126206,-0.114542,0.021880,-0.338177,...,-0.309268,0.025826,-0.248702,-0.058406,-0.003371,NaN,-0.030953,0.056977,-0.043212,-0.107470
AAAS_proteo,-0.133788,0.034448,-0.206183,-0.185359,1.000000,-0.108713,-0.069045,0.056345,-0.112788,0.096138,...,0.068744,-0.077652,0.017033,-0.064985,0.041987,0.051497,0.042336,0.176711,0.070072,0.042435
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,-0.079465,-0.003671,NaN,NaN,0.051497,-0.043763,-0.077952,-0.178135,0.049388,0.057847,...,0.334358,0.392807,0.263361,0.239298,0.293803,1.000000,0.489247,-0.015125,0.392807,-0.015125
ZYG11B_sommut,-0.157926,-0.051510,-0.043936,-0.030953,0.042336,0.107896,0.096594,0.040558,0.146915,0.004989,...,0.699462,0.392807,0.263361,0.239298,-0.034565,0.489247,1.000000,-0.015125,0.392807,-0.015125
ZYX_sommut,-0.124692,-0.097939,-0.107738,0.056977,0.176711,-0.018708,0.035532,-0.117483,-0.025104,-0.031500,...,-0.021624,-0.018625,-0.026780,-0.029090,-0.024311,-0.015125,-0.015125,1.000000,-0.018625,-0.010638
ZZEF1_sommut,-0.029678,0.058407,0.051249,-0.043212,0.070072,0.000094,0.034641,0.103176,0.106458,0.029150,...,0.261862,0.311594,0.200570,0.179468,0.227002,0.392807,0.392807,-0.018625,1.000000,-0.018625
ZZZ3_sommut,0.023839,0.048919,-0.156473,-0.107470,0.042435,-0.045870,0.177354,0.025093,-0.132443,0.048633,...,-0.021624,-0.018625,-0.026780,0.365703,-0.024311,-0.015125,-0.015125,-0.010638,-0.018625,1.000000

In [40]:
correlations.columns.str.contains('CTNNB1').sum()

2

In [12]:
correlations[correlations.columns.str.contains('CTNNB1')][['LEF1_proteo', 'LEF1_sommut']]

               LEF1_proteo  LEF1_sommut
CTNNB1_proteo     0.540913     0.103803
CTNNB1_sommut     0.512732     0.141714